//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asis_tablelistdisplay
    {
        public int IDAsisTableListDisplay { get; set; }
        public Nullable<int> IDAsisTableList { get; set; }
        public string SortID { get; set; }
        public string FieldName { get; set; }
        public string DisplayNL { get; set; }
        public string DisplayEN { get; set; }
        public string HelpNL { get; set; }
        public string HelpEN { get; set; }
        public Nullable<int> IDUserCreated { get; set; }
        public Nullable<int> IDUserModified { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
