//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asis_tablelog
    {
        public int IDAsisTableLog { get; set; }
        public Nullable<int> IDTableList { get; set; }
        public Nullable<int> RecordID { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> IDAttRecordOperation { get; set; }
        public Nullable<System.DateTime> DateOperation { get; set; }
        public string Logchange { get; set; }
    }
}
