//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsup_project
    {
        public int IDDSupProject { get; set; }
        public Nullable<int> IDRelPerson { get; set; }
        public Nullable<int> IDRelInstitution { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<System.DateTime> DateUltimo { get; set; }
        public Nullable<int> IDAttStatus { get; set; }
        public Nullable<double> AmountTotal { get; set; }
        public Nullable<double> AmountAsked { get; set; }
        public Nullable<double> AmountReceived { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectContent { get; set; }
        public Nullable<System.DateTime> DateSelect { get; set; }
        public Nullable<System.DateTime> DateResult { get; set; }
        public Nullable<int> IDUserCreated { get; set; }
        public Nullable<int> IDUserModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
