//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsup_family
    {
        public int IDDSupFamily { get; set; }
        public Nullable<int> IDRelPerson { get; set; }
        public Nullable<int> IDCoparent { get; set; }
        public Nullable<int> IDAttFamilyType { get; set; }
        public string NumberBSN { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string NumberSVB { get; set; }
        public string OtherOptions { get; set; }
        public Nullable<bool> HasOptionSometimes { get; set; }
        public Nullable<bool> HasPGB { get; set; }
        public Nullable<bool> HasPGBPaymentDSupport { get; set; }
        public Nullable<int> IDAttFoundDSupport { get; set; }
        public Nullable<bool> HasOptionTraining { get; set; }
        public Nullable<int> TrainingNumber { get; set; }
        public string TrainingMemo { get; set; }
        public Nullable<bool> HasDog { get; set; }
        public Nullable<bool> HasCat { get; set; }
        public Nullable<bool> HasStopped { get; set; }
        public Nullable<System.DateTime> DateRegistration { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<bool> HasDiabetes { get; set; }
        public string SpecialInfo { get; set; }
        public Nullable<int> NumberChildren { get; set; }
        public Nullable<bool> HasOptionSchoolvacation { get; set; }
        public Nullable<bool> HasOptionMidDay { get; set; }
        public Nullable<bool> HasOptionOneNight { get; set; }
        public Nullable<bool> HasOptionMoreNights { get; set; }
        public Nullable<bool> HasOptionWeekend { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> IDAttBrowser { get; set; }
        public Nullable<int> IDAttOS { get; set; }
        public Nullable<int> IDAttPhase { get; set; }
        public Nullable<int> IDAttRegistration { get; set; }
        public string Memo { get; set; }
        public string Mark { get; set; }
        public Nullable<bool> ContractMediation { get; set; }
        public Nullable<bool> ContractPGB { get; set; }
        public Nullable<int> IDUserCreated { get; set; }
        public Nullable<int> IDUserModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
