//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsup_stat
    {
        public int IDSupStat { get; set; }
        public Nullable<System.DateTime> DatumRapport { get; set; }
        public Nullable<int> Personen { get; set; }
        public Nullable<int> Instellingen { get; set; }
        public Nullable<int> Oppassers { get; set; }
        public Nullable<int> Gezinnen { get; set; }
        public Nullable<int> Kinderen { get; set; }
        public Nullable<int> KoppellingGezinOppasser { get; set; }
        public Nullable<int> VOGAangevraagd { get; set; }
        public Nullable<int> VOGToegekend { get; set; }
        public Nullable<int> NieuwsbriefAbonnees { get; set; }
        public Nullable<int> PGBAangevraagd { get; set; }
        public Nullable<int> PGBToegekend { get; set; }
        public Nullable<int> IDUserCreated { get; set; }
        public Nullable<int> IDUserModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
