//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsup_children
    {
        public int IDDSupChildren { get; set; }
        public Nullable<int> IDChild { get; set; }
        public Nullable<int> IDParent { get; set; }
        public string BSN { get; set; }
        public Nullable<System.DateTime> DateRegistration { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<bool> HasDiabetes { get; set; }
        public Nullable<System.DateTime> DateDiabetes { get; set; }
        public Nullable<int> IDAttTherapy { get; set; }
        public string TherapySpec { get; set; }
        public Nullable<bool> HasSensor { get; set; }
        public string SensorSpec { get; set; }
        public string Info { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> IDAttBrowser { get; set; }
        public Nullable<int> IDAttOS { get; set; }
        public Nullable<int> IDUserCreated { get; set; }
        public Nullable<int> IDUserModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
