//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsup_pgb
    {
        public int IDDSupPGB { get; set; }
        public Nullable<int> IDFamily { get; set; }
        public Nullable<int> IDDSupport { get; set; }
        public Nullable<System.DateTime> DateContract { get; set; }
        public Nullable<bool> Contract { get; set; }
        public Nullable<double> Fee { get; set; }
        public Nullable<System.DateTime> DateRequest { get; set; }
        public Nullable<System.DateTime> DateDecision { get; set; }
        public Nullable<bool> Granted { get; set; }
        public Nullable<int> IDUserCreated { get; set; }
        public Nullable<int> IDUserModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
