//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsup_carer
    {
        public int IDDSupCarer { get; set; }
        public Nullable<int> IDRelPerson { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> IDAttFoundDSupport { get; set; }
        public Nullable<int> IDAttEducation { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<bool> HasDiabetes { get; set; }
        public Nullable<bool> DiabetesExperience { get; set; }
        public Nullable<bool> CareExperience { get; set; }
        public Nullable<bool> InstrumentsExperience { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public string DiabetesMemo { get; set; }
        public string CareMemo { get; set; }
        public string InstrumentsMemo { get; set; }
        public Nullable<bool> IsVolunteer { get; set; }
        public string Motivation { get; set; }
        public string Education { get; set; }
        public string EduLanguage { get; set; }
        public Nullable<bool> HasEduLanguageMore { get; set; }
        public Nullable<int> IDAttEducationLevel { get; set; }
        public Nullable<bool> WantsTraining { get; set; }
        public Nullable<bool> HasVOG { get; set; }
        public Nullable<System.DateTime> DateVOGRequest { get; set; }
        public string RemarKVOG { get; set; }
        public Nullable<bool> HasCopyVOG { get; set; }
        public Nullable<int> DistanceMaxKM { get; set; }
        public Nullable<int> IDAttTransport { get; set; }
        public Nullable<bool> HasSocialBenefit { get; set; }
        public Nullable<bool> HasDogProblem { get; set; }
        public Nullable<bool> HasCatProblem { get; set; }
        public Nullable<bool> HasAllergy { get; set; }
        public string AllergyAnimals { get; set; }
        public Nullable<bool> OwnTransportNight { get; set; }
        public string NightWatch { get; set; }
        public string VacationWatch { get; set; }
        public Nullable<bool> IsGuesttParent { get; set; }
        public Nullable<bool> HasOptionSchoolvacation { get; set; }
        public Nullable<bool> HasOptionMidDay { get; set; }
        public Nullable<bool> HasOptionOneNight { get; set; }
        public Nullable<bool> HasOptionMoreNights { get; set; }
        public Nullable<bool> HasOptionWeekend { get; set; }
        public Nullable<bool> HasStopped { get; set; }
        public string ReasonStop { get; set; }
        public string Info { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> IDAttBrowser { get; set; }
        public Nullable<int> IDAttOS { get; set; }
        public Nullable<int> IDAttQualificationSupCarer { get; set; }
        public Nullable<int> IDAttQualificationDSupport { get; set; }
        public Nullable<int> IDAttPhase { get; set; }
        public Nullable<int> IDAttRegistration { get; set; }
        public string Mark { get; set; }
        public Nullable<bool> ContractMatch { get; set; }
        public Nullable<int> IDUserCreated { get; set; }
        public Nullable<int> IDUserModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
