//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsup_careravailable
    {
        public int IDDSupCarerAvailable { get; set; }
        public Nullable<int> IDDSupCarer { get; set; }
        public Nullable<bool> MorMon { get; set; }
        public Nullable<bool> MidMon { get; set; }
        public Nullable<bool> AftMon { get; set; }
        public Nullable<bool> EveMon { get; set; }
        public Nullable<bool> MorTue { get; set; }
        public Nullable<bool> MidTue { get; set; }
        public Nullable<bool> AftTue { get; set; }
        public Nullable<bool> EveTue { get; set; }
        public Nullable<bool> MorWed { get; set; }
        public Nullable<bool> MidWed { get; set; }
        public Nullable<bool> AftWed { get; set; }
        public Nullable<bool> EveWed { get; set; }
        public Nullable<bool> MorThu { get; set; }
        public Nullable<bool> MidThu { get; set; }
        public Nullable<bool> AftThu { get; set; }
        public Nullable<bool> EveThu { get; set; }
        public Nullable<bool> MorFri { get; set; }
        public Nullable<bool> MidFri { get; set; }
        public Nullable<bool> AftFri { get; set; }
        public Nullable<bool> EveFri { get; set; }
        public Nullable<bool> MorSat { get; set; }
        public Nullable<bool> MidSat { get; set; }
        public Nullable<bool> AftSat { get; set; }
        public Nullable<bool> EveSat { get; set; }
        public Nullable<bool> MorSun { get; set; }
        public Nullable<bool> MidSun { get; set; }
        public Nullable<bool> AftSun { get; set; }
        public Nullable<bool> EveSun { get; set; }
        public string Availability { get; set; }
        public Nullable<int> IDUserCreated { get; set; }
        public Nullable<int> IDUserModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
