//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_tablelistdisplay
    {
        public int IDTablelistDisplay { get; set; }
        public Nullable<int> IDTableList { get; set; }
        public Nullable<int> IDController { get; set; }
        public string Version { get; set; }
        public Nullable<bool> IsInIndex { get; set; }
        public Nullable<bool> IsInCreate { get; set; }
        public Nullable<bool> IsInEdit { get; set; }
        public Nullable<bool> IsInDetail { get; set; }
        public Nullable<bool> IsInExcel { get; set; }
        public Nullable<bool> IsMultiLingual { get; set; }
        public string SortID { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> IDAsisFieldType { get; set; }
        public string Display_NL { get; set; }
        public string Display_EN { get; set; }
        public string Help_NL { get; set; }
        public string Help_EN { get; set; }
        public Nullable<int> IDUserCreated { get; set; }
        public Nullable<int> IDUserModified { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
